site_name: BackupItAll

markdown_extensions:
  - toc:
      permalink: true

# markdown_extensions:
#   # - pymdownx.critic
#   - pymdownx.caret
#   - pymdownx.keys
#   - pymdownx.mark
#   - pymdownx.tilde

theme:
  name: null
  custom_dir: 'cinder'
nav:
  - Home: index.md
  - Documentation:
    - 'Installation': docu/install.md
    - 'Configuration': docu/configuration.md
    - 'Run in Docker': docu/run-in-docker.md
    # - 'Context of the organization': organisation/context-of-the-organisation.md
    # - 'Scope': organisation/scope.md
    # - 'Resources': organisation/resources.md
    # - 'Interested Parties: Stakeholders and their requirements': organisation/interested-parties.md
    # - 'Legal and regulatory requirements': organisation/legal-and-regulatory-requirements.md
    # - 'Suppliers': organisation/suppliers.md
    # - 'Roles and responsibilities': /organisation/roles-and-respnsibilities.md
    # - 'Information Security Policy': /organisation/information-security-policy.md
    # - 'Information security objectives': /organisation/information-security-objectives.md
    # - 'Key performance indicators and improvement': /organisation/kpis.md
    # - 'Measures': /organisation/measures.md
    # - 'Exceptions': /organisation/exceptions.md
    # - 'Communication': /organisation/communikation.md
    # - 'Emergency manual': /organisation/emergency-manual.md
    # - 'nonconformities': /organisation/nonconformities.md
